apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: Ben
spec:
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - server auth
  request:
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1V6Q0NBVHNDQVFBd0RqRU1NQW9HQTFVRUF3d0RZbVZ1TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBdkJEQmpKNVJiwfVm1udHJPbkl2M1d34rGbm5mcEEyZllQSnZiMXBrNW9kSFY4S0lHaitZCjhYMFlJa0VtSnlhLzFkTWl5NVAwNU5OMfnenFwZTBESVFWa3hlemZTU2lqV0ZubGNSTGVTMzZ6WHpDaDJ0VGhISTAKdm1wM3QxRUhrQk90c3FqaW92SUR1SHJVLys1dENjK2hSWmxVV0dnUUNpNWpmUmN3WWxmOUtqeXBoTmIyaXR2ZAo3Y0xJenFUdldBb2g0UmRJVURTVVZ6bmZudmg2QkVxQ1hUSko1QllhejlsU3NXQWYxUzdhamtCcWRYMEoxdVVZCk1uYjR6Y1ejfRVZ0luZy9RU3BUa25YWWlLR3dtdXpJN3RZVEwwSDZIeEoveGYra1ppVDZ3Q3A1fJvQUF3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFGMUQ1anB4enU2dEFIbHR6TVpjYW5VRHlTc01Cb2UwNzJmMXdOY3IxNW42elI0ZFFISnAwR3dhCnZ6T2s4d1NKSk1ZY0FlZUFvM1pBaC9aVlVmRnNCNE1NbEVDUU0vek5KZmVyMk5pYXg4WkMrekh1Ly8Kb2w5NGFlNjFhT2dmYkx1RvreG54di9vbU1IOWYwMDlIbWFNeG1KM0hFRGRza3dMY25kbUd6ZVprOGdPYzBKYUYxNgpmbWM3YzBpVmZWVUc4L3BDT2JzNzRCaytvOXY5fwfeFlNKzl4NklhR2JybzNIQThaOGxCQllDNitoRGw2R1FRNGNaCnFLOVNkVnFCR2NyanBUeVB2M2ZVMlE0ZWNPaUFCVFVZVGllVzlZOTRraXMzWHlNMVJrWUcrQWkyYWtqZVVhRkYKOHBzUktYZStObllodE5DMkJyUjRsTXlOMWFudlBzRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
