apiVersion: v1
kind: Deployment
metadata:
  name: nginx-test
spec:
  # 1. How many copies of each pod?
  replicas: 3

  # 2. How to update the pods?
  strategy: Recreate

  # 3. Which pods are managed by this deployment?
  selector:
    # Must match label
    matchLabels:
      deploy: example
  
  # regular pod configuration
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        deploy: example
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
