apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels: voting-app
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: voting app
